### ISSUE TITLE
Support Midi Active Sensing

### ISSUE THREAD

**Issue by hhoegelo** [nonlinear-labs-dev/midibridge#11]
It seems we have a problem with alsa usb support on the beaglebone: If the Midi bridge does not accept our messages, BBB will send it again and again and use up all available CPU. It can be reproduced by plugging the midi bridge into a PC, but not use the midi port there. As soon as you use the C15 ribbons, the Midi bridge led starts flashing red and the HWUI becomes unresponsive.
As soon as - for example - amidi uses the other bridge port, or the usb cable is unplugged, the problem disappears.

The solution could be, that all incoming midi data is accepted and thrown away, until Midi Active Sensing indicates there is actually someone listening on the other side.

**Comment by KlausStrohhaecker** [comment]
Closed after succesful discussion and code change on the bridge, using shorter blocking timeouts until packets are dropped.
